### ISSUE TITLE
Symbolicator Should Use AWS Credentials Provided to Running Container

### ISSUE THREAD

**Issue by phene** [getsentry/symbolicator#143]
Instead of `api/applecrashreport/` requiring credentials to be passed, it would be great if we could provide an AWS role + credentials on service start up for it to use with all S3 requests.

**Comment by jan-auer** [comment]
Hi @phene! It's not super clear from documentation, but you can specify `sources` in the config file. The schema of those sources is identical to the one documented here: https://getsentry.github.io/symbolicator/api/

Example `config.yml`:

```yml
cache_dir: "/tmp/symbolicator"
bind: 0.0.0.0:3021
sources:
- id: my-bucket-linux
  type: s3
  bucket: my-project-my-bucket
  region: us-east-1
  prefix: "/linux"
  access_key: AMVSAVWEXRIRJPOMCKWN
  secret_key: Lqnc45YWr9y7qftCI+vST/1ZPmmw1H6SkbIf2v/8
  filters:
    filetypes:
    - elf_debug
    - elf_code
  layout:
    type: native
    casing: lowercase
```

**Comment by phene** [comment]
That unfortunately that doesn't deal with the need for non-user tokens from assumed roles or instance profiles. We need to be able to use session_tokens in addition to the access and secret keys.

**Comment by jan-auer** [comment]
I see, thanks. Agree that this should be added to the S3 source.

**Comment by phene** [comment]
Is it possible to add support for a `credential_source`, similar to what [boto supports](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html)?

**Comment by troy-lamerton** [comment]
@jan-auer I specified `sources` in config.yml and the server still requires 
me to provide aws credentials in every request.

If I don't provide access_key, there is this response:

```json
{"detail":"missing field `access_key` at line 18 column 1"}
```

---

config.yml

```yaml
cache_dir: "/tmp/symbolicator"
bind: "0.0.0.0:3021"
logging:
  level: "debug"
  format: "pretty"
  enable_backtraces: true
sources:
  - id: ios-system-symbols
    type: s3
    bucket: gitlab-test-symbols
    region: us-east-2
    prefix: /sentry_symbolicator/ios_system/
    access_key: AMVSAVWEXRIRJPOMCKWN
    secret_key: Lqnc45YWr9y7qftCI+vST/1ZPmmw1H6SkbIf2v/8
    filters:
      filetypes:
      - mach_debug
      - mach_code
    layout:
      type: unified
      casing: lowercase
```

The "sources" json which causes error:

```json
[
    {
        "id": "ios-system-symbols",
        "type": "s3",
        "bucket": "gitlab-test-symbols",
        "region": "us-east-2",
        "prefix": "/sentry_symbolicator/ios_system",
        "filters": {
            "filetypes": [
                "mach_code"
            ]
        },
        "layout": {
            "type": "unified",
            "casing": "lowercase"
        }
    }
]
```

Error:

```json
{"detail":"missing field `access_key` at line 18 column 1"}
```
