### ISSUE TITLE
Failed to fetch symbol file from S3 if existing file on docker container is 0 bytes

### ISSUE THREAD

**Issue by Aashima89** [getsentry/symbolicator#199]
When symbol file at S3 is missing, symbolicator creates a 0bytes file locally on container. Hence it never updates with new file(if uploaded to S3). Only workaround seems to be restart the docker container. Can we not always looks for S3 files if existing is 0 bytes?

**Comment by untitaker** [comment]
there's an undocumented option `cache.retry_misses_after` for this.

**Comment by Aashima89** [comment]
Doesnt seem to work. Pasting my config.yaml 

`cache_dir: "/tmp/symbolicator"
bind: "0.0.0.0:3021"
logging:
  # level: "info"
  level: "trace"
  format: "pretty"
  enable_backtraces: true
metrics:
  statsd: "127.0.0.1:8125"
  prefix: "symbolicator"
sources:
  - id: whatever
    type: s3
    bucket: xxx
    region: us-west-2
    prefix: "/ios"
    access_key: xxx
    secret_key: xxx
    filters:
      filetypes:
      - mach_debug
      - mach_code
    layout:
      type: native
      casing: lowercase
cache:
    retry_misses_after: 0 `

**Comment by Aashima89** [comment]
this worked for  getsentry/symbolicator:cd545b3
```
caches:
  downloaded:
    retry_misses_after:
      secs: 0  
      nanos: 0
  derived:
    retry_misses_after:
      secs: 0
      nanos: 0
```
