### ISSUE TITLE
Error while downloading file: failed to fetch data from S3

### ISSUE THREAD

**Issue by mk4437** [getsentry/symbolicator#728]
### Environment

Self-hosted symbolicator 0.4.2 on amazonlinux2

### Steps to Reproduce

Send /applecrashreport requests

### Expected Result

No ERROR messages logged

### Actual Result

Similar to https://github.com/getsentry/symbolicator/issues/640, we intermittently see error messages like the following:

```
ERROR symbolicator::services::objects::data_cache > Error while downloading file: failed to fetch data from S3
caused by: expected value at line 1 column 1
caused by: expected value at line 1 column 1
```
We use two S3 buckets, one for system symbol files and another for application symbol files.  All files end without a suffix.  So four locations get searched for each symbol file (two S3 buckets, with and without .app).  The errors when they occur are for the non-existent locations.  

In spot-checking I do usually see the downloaded file in symcache, though in at least one case one of our instances showed size 0 in symcache.

Our cache settings are as follows:
```
caches:
  downloaded:
    retry_misses_after: 0s
  derived:
    retry_misses_after: 0s
```
and in each `sources` entry:
```
    filters:
      filetypes:
        - "mach_debug"
        - "mach_code"
    layout:
      type: "native"
      casing: "lowercase"
```
